name: Build for Apple Silicon

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Apple Silicon bundle
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies and configure environment
        run: |
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          brew update
          brew install qt

      - name: Configure Qt
        run: qmake netcatgui.pro

      - name: Build
        run: make -j$(sysctl -n hw.ncpu)

      - name: Sign the app
        run: codesign --sign - --force --deep build/netcatgui.app
        
      - name: Generate macOS app dmg
        run: hdiutil create -volname "NetcatGUI" -srcfolder build "NetcatGUI-arm64"

      - name: Upload artifacts - macOS
        uses: actions/upload-artifact@v4
        with:
          name: netcatgui-macOS-arm64
          path: build/NetcatGUI-arm64.dmg
          if-no-files-found: error